package com.nest.pariyavaram.repository

import com.nest.pariyavaram.local.ReportDao
import com.nest.pariyavaram.local.ReportStatus
import com.nest.pariyavaram.data.model.WasteReport
import kotlinx.coroutines.flow.Flow

class ReportRepository(private val dao: ReportDao) {

    /** Live stream of all reports, newest first. */
    val allReports: Flow<List<WasteReport>> = dao.getAllReports()

    /** Insert a new report. */
    suspend fun addReport(report: WasteReport) {
        dao.insertReport(report)
    }

    /**
     * Mark a report as cleaned by its numeric DB id.
     * @param id  WasteReport.id  (Int, auto-generated by Room)
     */
    suspend fun markAsCleaned(id: Int) {
        dao.updateStatus(id, ReportStatus.CLEANED.value)
    }

    /** Update the AI-suggested category for a report. */
    suspend fun updateAiCategory(id: Int, category: String) {
        dao.updateAiCategory(id, category)
    }
}